# Generated by Django 4.0.4 on 2022-04-28 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_controller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('CustomUser', 'User'), ('AdminUser', 'Admin')], default='User', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 28, 13, 15, 29, 821333, tzinfo=utc)),
        ),
    ]
