# Generated by Django 4.0.4 on 2022-05-03 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_controller', '0002_customuser_user_type_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 12, 57, 15, 379020, tzinfo=utc)),
        ),
    ]
