# Generated by Django 4.0.4 on 2022-05-03 21:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_controller', '0003_alter_customuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 21, 6, 53, 312646, tzinfo=utc)),
        ),
    ]
